-- Clear existing data
TRUNCATE TABLE countries;

-- Insert all countries
INSERT INTO countries (id, name, code) VALUES
(1, 'Afghanistan', 'AFG'),
(2, 'Albania', 'ALB'),
(3, 'Algeria', 'DZA'),
(4, 'Andorra', 'AND'),
(5, 'Angola', 'AGO'),
(6, 'Antigua and Barbuda', 'ATG'),
(7, 'Argentina', 'ARG'),
(8, 'Armenia', 'ARM'),
(9, 'Australia', 'AUS'),
(10, 'Austria', 'AUT'),
(11, 'Azerbaijan', 'AZE'),
(12, 'Bahamas', 'BHS'),
(13, 'Bahrain', 'BHR'),
(14, 'Bangladesh', 'BGD'),
(15, 'Barbados', 'BRB'),
(16, 'Belarus', 'BLR'),
(17, 'Belgium', 'BEL'),
(18, 'Belize', 'BLZ'),
(19, 'Benin', 'BEN'),
(20, 'Bhutan', 'BTN'),
(21, 'Bolivia', 'BOL'),
(22, 'Bosnia and Herzegovina', 'BIH'),
(23, 'Botswana', 'BWA'),
(24, 'Brazil', 'BRA'),
(25, 'Brunei', 'BRN'),
(26, 'Bulgaria', 'BGR'),
(27, 'Burkina Faso', 'BFA'),
(28, 'Burundi', 'BDI'),
(29, 'Cabo Verde', 'CPV'),
(30, 'Cambodia', 'KHM'),
(31, 'Cameroon', 'CMR'),
(32, 'Canada', 'CAN'),
(33, 'Central African Republic', 'CAF'),
(34, 'Chad', 'TCD'),
(35, 'Chile', 'CHL'),
(36, 'China', 'CHN'),
(37, 'Colombia', 'COL'),
(38, 'Comoros', 'COM'),
(39, 'Congo', 'COG'),
(40, 'Costa Rica', 'CRI'),
(41, 'Croatia', 'HRV'),
(42, 'Cuba', 'CUB'),
(43, 'Cyprus', 'CYP'),
(44, 'Czech Republic', 'CZE'),
(45, 'Democratic Republic of the Congo', 'COD'),
(46, 'Denmark', 'DNK'),
(47, 'Djibouti', 'DJI'),
(48, 'Dominica', 'DMA'),
(49, 'Dominican Republic', 'DOM'),
(50, 'Ecuador', 'ECU'),
(51, 'Egypt', 'EGY'),
(52, 'El Salvador', 'SLV'),
(53, 'Equatorial Guinea', 'GNQ'),
(54, 'Eritrea', 'ERI'),
(55, 'Estonia', 'EST'),
(56, 'Eswatini', 'SWZ'),
(57, 'Ethiopia', 'ETH'),
(58, 'Fiji', 'FJI'),
(59, 'Finland', 'FIN'),
(60, 'France', 'FRA'),
(61, 'Gabon', 'GAB'),
(62, 'Gambia', 'GMB'),
(63, 'Georgia', 'GEO'),
(64, 'Germany', 'DEU'),
(65, 'Ghana', 'GHA'),
(66, 'Greece', 'GRC'),
(67, 'Grenada', 'GRD'),
(68, 'Guatemala', 'GTM'),
(69, 'Guinea', 'GIN'),
(70, 'Guinea-Bissau', 'GNB'),
(71, 'Guyana', 'GUY'),
(72, 'Haiti', 'HTI'),
(73, 'Honduras', 'HND'),
(74, 'Hungary', 'HUN'),
(75, 'Iceland', 'ISL'),
(76, 'India', 'IND'),
(77, 'Indonesia', 'IDN'),
(78, 'Iran', 'IRN'),
(79, 'Iraq', 'IRQ'),
(80, 'Ireland', 'IRL'),
(81, 'Israel', 'ISR'),
(82, 'Italy', 'ITA'),
(83, 'Jamaica', 'JAM'),
(84, 'Japan', 'JPN'),
(85, 'Jordan', 'JOR'),
(86, 'Kazakhstan', 'KAZ'),
(87, 'Kenya', 'KEN'),
(88, 'Kiribati', 'KIR'),
(89, 'Kuwait', 'KWT'),
(90, 'Kyrgyzstan', 'KGZ'),
(91, 'Laos', 'LAO'),
(92, 'Latvia', 'LVA'),
(93, 'Lebanon', 'LBN'),
(94, 'Lesotho', 'LSO'),
(95, 'Liberia', 'LBR'),
(96, 'Libya', 'LBY'),
(97, 'Liechtenstein', 'LIE'),
(98, 'Lithuania', 'LTU'),
(99, 'Luxembourg', 'LUX'),
(100, 'Madagascar', 'MDG'),
(101, 'Malawi', 'MWI'),
(102, 'Malaysia', 'MYS'),
(103, 'Maldives', 'MDV'),
(104, 'Mali', 'MLI'),
(105, 'Malta', 'MLT'),
(106, 'Marshall Islands', 'MHL'),
(107, 'Mauritania', 'MRT'),
(108, 'Mauritius', 'MUS'),
(109, 'Mexico', 'MEX'),
(110, 'Micronesia', 'FSM'),
(111, 'Moldova', 'MDA'),
(112, 'Monaco', 'MCO'),
(113, 'Mongolia', 'MNG'),
(114, 'Montenegro', 'MNE'),
(115, 'Morocco', 'MAR'),
(116, 'Mozambique', 'MOZ'),
(117, 'Myanmar', 'MMR'),
(118, 'Namibia', 'NAM'),
(119, 'Nauru', 'NRU'),
(120, 'Nepal', 'NPL'),
(121, 'Netherlands', 'NLD'),
(122, 'New Zealand', 'NZL'),
(123, 'Nicaragua', 'NIC'),
(124, 'Niger', 'NER'),
(125, 'Nigeria', 'NGA'),
(126, 'North Korea', 'PRK'),
(127, 'North Macedonia', 'MKD'),
(128, 'Norway', 'NOR'),
(129, 'Oman', 'OMN'),
(130, 'Pakistan', 'PAK'),
(131, 'Palau', 'PLW'),
(132, 'Panama', 'PAN'),
(133, 'Papua New Guinea', 'PNG'),
(134, 'Paraguay', 'PRY'),
(135, 'Peru', 'PER'),
(136, 'Philippines', 'PHL'),
(137, 'Poland', 'POL'),
(138, 'Portugal', 'PRT'),
(139, 'Qatar', 'QAT'),
(140, 'Romania', 'ROU'),
(141, 'Russia', 'RUS'),
(142, 'Rwanda', 'RWA'),
(143, 'Saint Kitts and Nevis', 'KNA'),
(144, 'Saint Lucia', 'LCA'),
(145, 'Saint Vincent and the Grenadines', 'VCT'),
(146, 'Samoa', 'WSM'),
(147, 'San Marino', 'SMR'),
(148, 'Sao Tome and Principe', 'STP'),
(149, 'Saudi Arabia', 'SAU'),
(150, 'Senegal', 'SEN'),
(151, 'Serbia', 'SRB'),
(152, 'Seychelles', 'SYC'),
(153, 'Sierra Leone', 'SLE'),
(154, 'Singapore', 'SGP'),
(155, 'Slovakia', 'SVK'),
(156, 'Slovenia', 'SVN'),
(157, 'Solomon Islands', 'SLB'),
(158, 'Somalia', 'SOM'),
(159, 'South Africa', 'ZAF'),
(160, 'South Korea', 'KOR'),
(161, 'South Sudan', 'SSD'),
(162, 'Spain', 'ESP'),
(163, 'Sri Lanka', 'LKA'),
(164, 'Sudan', 'SDN'),
(165, 'Suriname', 'SUR'),
(166, 'Sweden', 'SWE'),
(167, 'Switzerland', 'CHE'),
(168, 'Syria', 'SYR'),
(169, 'Taiwan', 'TWN'),
(170, 'Tajikistan', 'TJK'),
(171, 'Tanzania', 'TZA'),
(172, 'Thailand', 'THA'),
(173, 'Timor-Leste', 'TLS'),
(174, 'Togo', 'TGO'),
(175, 'Tonga', 'TON'),
(176, 'Trinidad and Tobago', 'TTO'),
(177, 'Tunisia', 'TUN'),
(178, 'Turkey', 'TUR'),
(179, 'Turkmenistan', 'TKM'),
(180, 'Tuvalu', 'TUV'),
(181, 'Uganda', 'UGA'),
(182, 'Ukraine', 'UKR'),
(183, 'United Arab Emirates', 'ARE'),
(184, 'United Kingdom', 'GBR'),
(185, 'United States', 'USA'),
(186, 'Uruguay', 'URY'),
(187, 'Uzbekistan', 'UZB'),
(188, 'Vanuatu', 'VUT'),
(189, 'Vatican City', 'VAT'),
(190, 'Venezuela', 'VEN'),
(191, 'Vietnam', 'VNM'),
(192, 'Yemen', 'YEM'),
(193, 'Zambia', 'ZMB'),
(194, 'Zimbabwe', 'ZWE');
